
package ttu.idu0080.courierservice.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-04-15T10:41:25.889+03:00
 * Generated source version: 2.6.16
 * 
 */
public final class CourierService_CourierServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.order.idu0080.ttu/", "CourierServiceService");

    public CourierService_CourierServicePort_Client() {
    }
    public List<ttu.idu0080.courierservice.client.Courier> getAllCouriers() throws Exception {
        URL wsdlURL = new URL("http://localhost:8080/My_bprotsess/services/WsPort?wsdl");//CourierServiceService.WSDL_LOCATION;

   	 	List<ttu.idu0080.courierservice.client.Courier> _getAllCouriers__return = null ;
     
        CourierServiceService ss = new CourierServiceService(wsdlURL, SERVICE_NAME);
        CourierService port = ss.getCourierServicePort();  
        
        {
        _getAllCouriers__return = port.getAllCouriers();
        }
        return _getAllCouriers__return;
    }
    
    public ttu.idu0080.courierservice.client.Courier getCourierById(int courierId) throws Exception {
        URL wsdlURL = CourierServiceService.WSDL_LOCATION;

   	 	ttu.idu0080.courierservice.client.Courier _getCourier__return = null ;
      
        CourierServiceService ss = new CourierServiceService(wsdlURL, SERVICE_NAME);
        CourierService port = ss.getCourierServicePort();  
        
        {
        _getCourier__return = port.getCourierById(courierId);
        }

        return _getCourier__return;
    }
}
