
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.courierservice.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-04-15T10:41:25.952+03:00
 * Generated source version: 2.6.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "CourierServiceService",
                      portName = "CourierServicePort",
                      targetNamespace = "http://server.order.idu0080.ttu/",
                      wsdlLocation = "localhost:8090/mockCourierServicePortBinding?WSDL",
                      endpointInterface = "ttu.idu0080.courierservice.client.CourierService")
                      
public class CourierServiceImpl implements CourierService {

    private static final Logger LOG = Logger.getLogger(CourierServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.courierservice.client.CourierService#getAllCouriers(*
     */
    public java.util.List<ttu.idu0080.courierservice.client.Courier> getAllCouriers() { 
        LOG.info("Executing operation getAllCouriers");
        try {
            java.util.List<ttu.idu0080.courierservice.client.Courier> _return = new java.util.ArrayList<ttu.idu0080.courierservice.client.Courier>();
            ttu.idu0080.courierservice.client.Courier _returnVal1 = new ttu.idu0080.courierservice.client.Courier();
            java.util.List<ttu.idu0080.courierservice.client.EntAddress> _returnVal1Addresses = new java.util.ArrayList<ttu.idu0080.courierservice.client.EntAddress>();
            ttu.idu0080.courierservice.client.EntAddress _returnVal1AddressesVal1 = new ttu.idu0080.courierservice.client.EntAddress();
            _returnVal1AddressesVal1.setAddress(-804581653);
            _returnVal1AddressesVal1.setCountry("Country2126209250");
            _returnVal1AddressesVal1.setCounty("County-1284981667");
            _returnVal1AddressesVal1.setStreetAddress("StreetAddress732751210");
            _returnVal1AddressesVal1.setTownVillage("TownVillage-2000067186");
            _returnVal1AddressesVal1.setZipcode("Zipcode330092283");
            _returnVal1Addresses.add(_returnVal1AddressesVal1);
            _returnVal1.getAddresses().addAll(_returnVal1Addresses);
            _returnVal1.setEnterprise(-24335431);
            _returnVal1.setName("Name602104408");
            _returnVal1.setPercentFromOrder(-1756795390);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.courierservice.client.CourierService#getCouriersByAddress(java.lang.String  country ,)java.lang.String  county )*
     */
    public java.util.List<ttu.idu0080.courierservice.client.Courier> getCouriersByAddress(java.lang.String country,java.lang.String county) { 
        LOG.info("Executing operation getCouriersByAddress");
        System.out.println(country);
        System.out.println(county);
        try {
            java.util.List<ttu.idu0080.courierservice.client.Courier> _return = new java.util.ArrayList<ttu.idu0080.courierservice.client.Courier>();
            ttu.idu0080.courierservice.client.Courier _returnVal1 = new ttu.idu0080.courierservice.client.Courier();
            java.util.List<ttu.idu0080.courierservice.client.EntAddress> _returnVal1Addresses = new java.util.ArrayList<ttu.idu0080.courierservice.client.EntAddress>();
            ttu.idu0080.courierservice.client.EntAddress _returnVal1AddressesVal1 = new ttu.idu0080.courierservice.client.EntAddress();
            _returnVal1AddressesVal1.setAddress(-745457134);
            _returnVal1AddressesVal1.setCountry("Country639599556");
            _returnVal1AddressesVal1.setCounty("County1297320600");
            _returnVal1AddressesVal1.setStreetAddress("StreetAddress-1941942809");
            _returnVal1AddressesVal1.setTownVillage("TownVillage-1260857416");
            _returnVal1AddressesVal1.setZipcode("Zipcode-1363443305");
            _returnVal1Addresses.add(_returnVal1AddressesVal1);
            _returnVal1.getAddresses().addAll(_returnVal1Addresses);
            _returnVal1.setEnterprise(-1476234794);
            _returnVal1.setName("Name-2048550639");
            _returnVal1.setPercentFromOrder(-2024739232);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.courierservice.client.CourierService#getCourierById(int  courierId )*
     */
    public ttu.idu0080.courierservice.client.Courier getCourierById(int courierId) { 
        LOG.info("Executing operation getCourierById");
        System.out.println(courierId);
        try {
            ttu.idu0080.courierservice.client.Courier _return = new ttu.idu0080.courierservice.client.Courier();
            java.util.List<ttu.idu0080.courierservice.client.EntAddress> _returnAddresses = new java.util.ArrayList<ttu.idu0080.courierservice.client.EntAddress>();
            ttu.idu0080.courierservice.client.EntAddress _returnAddressesVal1 = new ttu.idu0080.courierservice.client.EntAddress();
            _returnAddressesVal1.setAddress(-408941720);
            _returnAddressesVal1.setCountry("Country-2067657147");
            _returnAddressesVal1.setCounty("County2070010475");
            _returnAddressesVal1.setStreetAddress("StreetAddress1264645753");
            _returnAddressesVal1.setTownVillage("TownVillage-773800433");
            _returnAddressesVal1.setZipcode("Zipcode672043475");
            _returnAddresses.add(_returnAddressesVal1);
            _return.getAddresses().addAll(_returnAddresses);
            _return.setEnterprise(-954054889);
            _return.setName("Name-1479526210");
            _return.setPercentFromOrder(-1623634234);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
