
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.offerservice;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.apache.log4j.Logger;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-04-15T10:32:47.383+03:00
 * Generated source version: 2.6.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "OfferServiceService",
                      portName = "OfferServicePort",
                      targetNamespace = "http://offerservice.idu0080.ttu/",
                      wsdlLocation = "file:/C:/Users/Gummel/ttu_mag2/veebiteenus/My_service/WebContent/WEB-INF/wsdl/offer.wsdl",
                      endpointInterface = "ttu.idu0080.offerservice.OfferService")
                      
public class OfferServiceImpl implements OfferService {

    private static final Logger LOG = Logger.getLogger(OfferServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.offerservice.OfferService#getOffer(int  courierId ,)ttu.idu0080.offerservice.Order  order )*
     */
    public ttu.idu0080.offerservice.Offer getOffer(int courierId,ttu.idu0080.offerservice.Order order) { 
    	LOG.info("------------------------------------------");
    	LOG.info("------------------------------------------");
    	LOG.info("OfferService starts");
        LOG.info("Revieved courier id: ["+courierId+"] order price: ["+order.getPriceTotal()+"] shipping address county: [" +order.getShippingAddress().getCounty()+ "]" );
  	   try {
  	       ttu.idu0080.courierservice.client.CourierService_CourierServicePort_Client courierService =
  	      		   new ttu.idu0080.courierservice.client.CourierService_CourierServicePort_Client();
  	       ttu.idu0080.courierservice.client.Courier courier = courierService.getCourierById(courierId);
  	       ttu.idu0080.offerservice.Offer _returnVal1 = new ttu.idu0080.offerservice.Offer();
  	        
  	       LOG.info("Kullerfirma protsent:["+courier.getPercentFromOrder()+"]");
  	       _returnVal1.setOfferId(generateOfferId());
  	       _returnVal1.setPrice(calculatePrice(courier, order));
  	       _returnVal1.setDeliveryDate(randInt(1,7));;
  	       
  	     LOG.info("Offer : offer_id: ["+_returnVal1.getOfferId()+"] offer price: [" 
  	    		 + _returnVal1.getPrice()+ "] approx. delivery date :[ +" +_returnVal1.getDeliveryDate()+"] days");
  	   LOG.info("OfferService ends");  
  	     return _returnVal1;
  	   } catch (java.lang.Exception ex) {
  	       ex.printStackTrace();
  	       throw new RuntimeException(ex);
  	   }
    }
    
    public float calculatePrice(ttu.idu0080.courierservice.client.Courier courier, ttu.idu0080.offerservice.Order order) {
 		float discount = 0;
 		for(ttu.idu0080.courierservice.client.EntAddress address : courier.getAddresses()) {
 			if(order.getShippingAddress().getCounty().equals(address.getCounty())) {
 				 LOG.info("Shipping address langeb kokku kullerfirma aadressiga\n");
 				 
 				discount += 30;
 				break;
 			}	
 		}
 		for(ttu.idu0080.courierservice.client.EntAddress address : courier.getAddresses()) {
 			for (ttu.idu0080.offerservice.EntAddress sellerAddr : order.getSeller().getAddresses()) {
 				if(sellerAddr.getCounty().equals(address.getCounty())) {
 					discount += 30; 
 					break;
 				}
 			}
 		}
 		LOG.info("Offer discount % ["+discount+"%]");
 		return (courier.getPercentFromOrder()*order.getPriceTotal())/100*(100-discount)/100;
 	}
 	
 	public static int randInt(int min, int max) {
 	   java.util.Random rand = new java.util.Random();
 	   int randomNum = rand.nextInt((max - min) + 1) + min;
 	   return randomNum;
 	}
 	
 	public String generateOfferId() {
 		String id = "";
 		java.util.Random r = new java.util.Random();
 		java.util.Random randomBoolean = new java.util.Random();
 		// 'a'=97, 'z'=122
 		for(int i = 0; i < 11; i ++ ) {
 			boolean b = randomBoolean.nextBoolean();
 			if(b) {
 			    int j = 97 + r.nextInt(122-97);
 			    id += (char) j +"";
 			} else {
 				int j = randInt(1,9);
 				id += j + "";
 			}
 		}
 		return id.toUpperCase();
 	}

}
