package ttu.idu0080.orderservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-04-15T10:40:20.806+03:00
 * Generated source version: 2.6.16
 * 
 */
@WebService(targetNamespace = "http://server.order.idu0080.ttu/", name = "OrderService")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderService {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://server.order.idu0080.ttu/OrderService/getOrdersByOrderIdRequest", output = "http://server.order.idu0080.ttu/OrderService/getOrdersByOrderIdResponse")
    @RequestWrapper(localName = "getOrdersByOrderId", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.client.GetOrdersByOrderId")
    @WebMethod
    @ResponseWrapper(localName = "getOrdersByOrderIdResponse", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.client.GetOrdersByOrderIdResponse")
    public ttu.idu0080.orderservice.client.Order getOrdersByOrderId(
        @WebParam(name = "order_id", targetNamespace = "")
        int orderId
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://server.order.idu0080.ttu/OrderService/getOrdersByCustomerIdRequest", output = "http://server.order.idu0080.ttu/OrderService/getOrdersByCustomerIdResponse")
    @RequestWrapper(localName = "getOrdersByCustomerId", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.client.GetOrdersByCustomerId")
    @WebMethod
    @ResponseWrapper(localName = "getOrdersByCustomerIdResponse", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.client.GetOrdersByCustomerIdResponse")
    public java.util.List<ttu.idu0080.orderservice.client.Order> getOrdersByCustomerId(
        @WebParam(name = "customer_id", targetNamespace = "")
        int customerId
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://server.order.idu0080.ttu/OrderService/getAllOrdersRequest", output = "http://server.order.idu0080.ttu/OrderService/getAllOrdersResponse")
    @RequestWrapper(localName = "getAllOrders", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.client.GetAllOrders")
    @WebMethod
    @ResponseWrapper(localName = "getAllOrdersResponse", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.client.GetAllOrdersResponse")
    public java.util.List<ttu.idu0080.orderservice.client.Order> getAllOrders();

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://server.order.idu0080.ttu/OrderService/getOrdersByShippingAddressRequest", output = "http://server.order.idu0080.ttu/OrderService/getOrdersByShippingAddressResponse")
    @RequestWrapper(localName = "getOrdersByShippingAddress", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.client.GetOrdersByShippingAddress")
    @WebMethod
    @ResponseWrapper(localName = "getOrdersByShippingAddressResponse", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.client.GetOrdersByShippingAddressResponse")
    public java.util.List<ttu.idu0080.orderservice.client.Order> getOrdersByShippingAddress(
        @WebParam(name = "country", targetNamespace = "")
        java.lang.String country,
        @WebParam(name = "county", targetNamespace = "")
        java.lang.String county
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://server.order.idu0080.ttu/OrderService/getOrdersByCustomerLastNameRequest", output = "http://server.order.idu0080.ttu/OrderService/getOrdersByCustomerLastNameResponse")
    @RequestWrapper(localName = "getOrdersByCustomerLastName", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.client.GetOrdersByCustomerLastName")
    @WebMethod
    @ResponseWrapper(localName = "getOrdersByCustomerLastNameResponse", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.orderservice.client.GetOrdersByCustomerLastNameResponse")
    public java.util.List<ttu.idu0080.orderservice.client.Order> getOrdersByCustomerLastName(
        @WebParam(name = "last_name", targetNamespace = "")
        java.lang.String lastName
    );
}
