
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.orderservice.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-04-15T10:40:20.759+03:00
 * Generated source version: 2.6.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderServiceService",
                      portName = "OrderServicePort",
                      targetNamespace = "http://server.order.idu0080.ttu/",
                      wsdlLocation = "http://localhost:8090/mockOrderServicePortBinding?WSDL",
                      endpointInterface = "ttu.idu0080.orderservice.client.OrderService")
                      
public class OrderServiceImpl implements OrderService {

    private static final Logger LOG = Logger.getLogger(OrderServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.orderservice.client.OrderService#getOrdersByOrderId(int  orderId )*
     */
    public ttu.idu0080.orderservice.client.Order getOrdersByOrderId(int orderId) { 
        LOG.info("Executing operation getOrdersByOrderId");
        System.out.println(orderId);
        try {
            ttu.idu0080.orderservice.client.Order _return = new ttu.idu0080.orderservice.client.Order();
            ttu.idu0080.orderservice.client.Customer _returnCustomer = new ttu.idu0080.orderservice.client.Customer();
            java.util.List<ttu.idu0080.orderservice.client.Address> _returnCustomerAddresses = new java.util.ArrayList<ttu.idu0080.orderservice.client.Address>();
            ttu.idu0080.orderservice.client.Address _returnCustomerAddressesVal1 = new ttu.idu0080.orderservice.client.Address();
            _returnCustomerAddressesVal1.setAddress(-1208741517);
            _returnCustomerAddressesVal1.setCountry("Country-1023548677");
            _returnCustomerAddressesVal1.setCounty("County-1242884147");
            _returnCustomerAddressesVal1.setStreetAddress("StreetAddress-1586642696");
            _returnCustomerAddressesVal1.setTownVillage("TownVillage-2032281924");
            _returnCustomerAddressesVal1.setZipcode("Zipcode-1817383674");
            _returnCustomerAddresses.add(_returnCustomerAddressesVal1);
            _returnCustomer.getAddresses().addAll(_returnCustomerAddresses);
            _returnCustomer.setCustomer(374679904);
            _returnCustomer.setFirstName("FirstName-1825157228");
            _returnCustomer.setLastName("LastName1052807127");
            _return.setCustomer(_returnCustomer);
            _return.setOrderId(1480411365);
            java.util.List<ttu.idu0080.orderservice.client.OrderProduct> _returnOrderProducts = new java.util.ArrayList<ttu.idu0080.orderservice.client.OrderProduct>();
            ttu.idu0080.orderservice.client.OrderProduct _returnOrderProductsVal1 = new ttu.idu0080.orderservice.client.OrderProduct();
            _returnOrderProductsVal1.setOrderProduct(123257633);
            _returnOrderProductsVal1.setPrice(0.76556647f);
            _returnOrderProductsVal1.setPriceTotal(0.8586586f);
            _returnOrderProductsVal1.setProductCount(1039103649);
            _returnOrderProductsVal1.setProductName("ProductName-2082063743");
            _returnOrderProducts.add(_returnOrderProductsVal1);
            _return.getOrderProducts().addAll(_returnOrderProducts);
            _return.setPriceTotal(0.35454863f);
            ttu.idu0080.orderservice.client.Seller _returnSeller = new ttu.idu0080.orderservice.client.Seller();
            java.util.List<ttu.idu0080.orderservice.client.EntAddress> _returnSellerAddresses = new java.util.ArrayList<ttu.idu0080.orderservice.client.EntAddress>();
            ttu.idu0080.orderservice.client.EntAddress _returnSellerAddressesVal1 = new ttu.idu0080.orderservice.client.EntAddress();
            _returnSellerAddressesVal1.setAddress(-2112732377);
            _returnSellerAddressesVal1.setCountry("Country-1456087804");
            _returnSellerAddressesVal1.setCounty("County1814414522");
            _returnSellerAddressesVal1.setStreetAddress("StreetAddress2122611749");
            _returnSellerAddressesVal1.setTownVillage("TownVillage1078443728");
            _returnSellerAddressesVal1.setZipcode("Zipcode1802234991");
            _returnSellerAddresses.add(_returnSellerAddressesVal1);
            _returnSeller.getAddresses().addAll(_returnSellerAddresses);
            _returnSeller.setEnterprise(-517225711);
            _returnSeller.setName("Name-1524442343");
            _return.setSeller(_returnSeller);
            ttu.idu0080.orderservice.client.Address _returnShippingAddress = new ttu.idu0080.orderservice.client.Address();
            _returnShippingAddress.setAddress(560175800);
            _returnShippingAddress.setCountry("Country-765715733");
            _returnShippingAddress.setCounty("County-68219046");
            _returnShippingAddress.setStreetAddress("StreetAddress-994241395");
            _returnShippingAddress.setTownVillage("TownVillage1476986523");
            _returnShippingAddress.setZipcode("Zipcode136383869");
            _return.setShippingAddress(_returnShippingAddress);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.orderservice.client.OrderService#getOrdersByCustomerId(int  customerId )*
     */
    public java.util.List<ttu.idu0080.orderservice.client.Order> getOrdersByCustomerId(int customerId) { 
        LOG.info("Executing operation getOrdersByCustomerId");
        System.out.println(customerId);
        try {
            java.util.List<ttu.idu0080.orderservice.client.Order> _return = new java.util.ArrayList<ttu.idu0080.orderservice.client.Order>();
            ttu.idu0080.orderservice.client.Order _returnVal1 = new ttu.idu0080.orderservice.client.Order();
            ttu.idu0080.orderservice.client.Customer _returnVal1Customer = new ttu.idu0080.orderservice.client.Customer();
            java.util.List<ttu.idu0080.orderservice.client.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.orderservice.client.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(-591852351);
            _returnVal1Customer.setFirstName("FirstName35821406");
            _returnVal1Customer.setLastName("LastName229298243");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(635404989);
            java.util.List<ttu.idu0080.orderservice.client.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.orderservice.client.OrderProduct>();
            ttu.idu0080.orderservice.client.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.orderservice.client.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(1165983942);
            _returnVal1OrderProductsVal1.setPrice(0.6630704f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.3959893f);
            _returnVal1OrderProductsVal1.setProductCount(-1919167831);
            _returnVal1OrderProductsVal1.setProductName("ProductName1511291017");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.36977714f);
            ttu.idu0080.orderservice.client.Seller _returnVal1Seller = new ttu.idu0080.orderservice.client.Seller();
            java.util.List<ttu.idu0080.orderservice.client.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.orderservice.client.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(-134524830);
            _returnVal1Seller.setName("Name-1605953610");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.orderservice.client.Address _returnVal1ShippingAddress = new ttu.idu0080.orderservice.client.Address();
            _returnVal1ShippingAddress.setAddress(756596295);
            _returnVal1ShippingAddress.setCountry("Country-1054424087");
            _returnVal1ShippingAddress.setCounty("County-40305735");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress307057960");
            _returnVal1ShippingAddress.setTownVillage("TownVillage-1537105116");
            _returnVal1ShippingAddress.setZipcode("Zipcode435394375");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.orderservice.client.OrderService#getAllOrders(*
     */
    public java.util.List<ttu.idu0080.orderservice.client.Order> getAllOrders() { 
        LOG.info("Executing operation getAllOrders");
        try {
            java.util.List<ttu.idu0080.orderservice.client.Order> _return = new java.util.ArrayList<ttu.idu0080.orderservice.client.Order>();
            ttu.idu0080.orderservice.client.Order _returnVal1 = new ttu.idu0080.orderservice.client.Order();
            ttu.idu0080.orderservice.client.Customer _returnVal1Customer = new ttu.idu0080.orderservice.client.Customer();
            java.util.List<ttu.idu0080.orderservice.client.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.orderservice.client.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(1857794840);
            _returnVal1Customer.setFirstName("FirstName-340840798");
            _returnVal1Customer.setLastName("LastName860561706");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(1300184663);
            java.util.List<ttu.idu0080.orderservice.client.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.orderservice.client.OrderProduct>();
            ttu.idu0080.orderservice.client.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.orderservice.client.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(919794475);
            _returnVal1OrderProductsVal1.setPrice(0.43077117f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.4120422f);
            _returnVal1OrderProductsVal1.setProductCount(-521964360);
            _returnVal1OrderProductsVal1.setProductName("ProductName-1854782394");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.5254295f);
            ttu.idu0080.orderservice.client.Seller _returnVal1Seller = new ttu.idu0080.orderservice.client.Seller();
            java.util.List<ttu.idu0080.orderservice.client.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.orderservice.client.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(1630450496);
            _returnVal1Seller.setName("Name-849347690");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.orderservice.client.Address _returnVal1ShippingAddress = new ttu.idu0080.orderservice.client.Address();
            _returnVal1ShippingAddress.setAddress(1966581382);
            _returnVal1ShippingAddress.setCountry("Country1037512590");
            _returnVal1ShippingAddress.setCounty("County1970347411");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress1299750684");
            _returnVal1ShippingAddress.setTownVillage("TownVillage-2123752393");
            _returnVal1ShippingAddress.setZipcode("Zipcode-1547119503");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.orderservice.client.OrderService#getOrdersByShippingAddress(java.lang.String  country ,)java.lang.String  county )*
     */
    public java.util.List<ttu.idu0080.orderservice.client.Order> getOrdersByShippingAddress(java.lang.String country,java.lang.String county) { 
        LOG.info("Executing operation getOrdersByShippingAddress");
        System.out.println(country);
        System.out.println(county);
        try {
            java.util.List<ttu.idu0080.orderservice.client.Order> _return = new java.util.ArrayList<ttu.idu0080.orderservice.client.Order>();
            ttu.idu0080.orderservice.client.Order _returnVal1 = new ttu.idu0080.orderservice.client.Order();
            ttu.idu0080.orderservice.client.Customer _returnVal1Customer = new ttu.idu0080.orderservice.client.Customer();
            java.util.List<ttu.idu0080.orderservice.client.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.orderservice.client.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(521091935);
            _returnVal1Customer.setFirstName("FirstName2078908199");
            _returnVal1Customer.setLastName("LastName-536086923");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(1606407682);
            java.util.List<ttu.idu0080.orderservice.client.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.orderservice.client.OrderProduct>();
            ttu.idu0080.orderservice.client.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.orderservice.client.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(1922366002);
            _returnVal1OrderProductsVal1.setPrice(0.24874014f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.48319674f);
            _returnVal1OrderProductsVal1.setProductCount(1147422546);
            _returnVal1OrderProductsVal1.setProductName("ProductName182278622");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.5177308f);
            ttu.idu0080.orderservice.client.Seller _returnVal1Seller = new ttu.idu0080.orderservice.client.Seller();
            java.util.List<ttu.idu0080.orderservice.client.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.orderservice.client.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(1899045573);
            _returnVal1Seller.setName("Name-905849889");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.orderservice.client.Address _returnVal1ShippingAddress = new ttu.idu0080.orderservice.client.Address();
            _returnVal1ShippingAddress.setAddress(-2037094344);
            _returnVal1ShippingAddress.setCountry("Country-2075454894");
            _returnVal1ShippingAddress.setCounty("County-683900303");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress-640102106");
            _returnVal1ShippingAddress.setTownVillage("TownVillage2079765789");
            _returnVal1ShippingAddress.setZipcode("Zipcode-47045705");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.orderservice.client.OrderService#getOrdersByCustomerLastName(java.lang.String  lastName )*
     */
    public java.util.List<ttu.idu0080.orderservice.client.Order> getOrdersByCustomerLastName(java.lang.String lastName) { 
        LOG.info("Executing operation getOrdersByCustomerLastName");
        System.out.println(lastName);
        try {
            java.util.List<ttu.idu0080.orderservice.client.Order> _return = new java.util.ArrayList<ttu.idu0080.orderservice.client.Order>();
            ttu.idu0080.orderservice.client.Order _returnVal1 = new ttu.idu0080.orderservice.client.Order();
            ttu.idu0080.orderservice.client.Customer _returnVal1Customer = new ttu.idu0080.orderservice.client.Customer();
            java.util.List<ttu.idu0080.orderservice.client.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.orderservice.client.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(-2080634136);
            _returnVal1Customer.setFirstName("FirstName896947580");
            _returnVal1Customer.setLastName("LastName-2126150987");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(-1518590830);
            java.util.List<ttu.idu0080.orderservice.client.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.orderservice.client.OrderProduct>();
            ttu.idu0080.orderservice.client.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.orderservice.client.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(-132973633);
            _returnVal1OrderProductsVal1.setPrice(0.48618174f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.7581666f);
            _returnVal1OrderProductsVal1.setProductCount(896004024);
            _returnVal1OrderProductsVal1.setProductName("ProductName-1031537035");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.17847621f);
            ttu.idu0080.orderservice.client.Seller _returnVal1Seller = new ttu.idu0080.orderservice.client.Seller();
            java.util.List<ttu.idu0080.orderservice.client.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.orderservice.client.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(1981795196);
            _returnVal1Seller.setName("Name-1339548769");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.orderservice.client.Address _returnVal1ShippingAddress = new ttu.idu0080.orderservice.client.Address();
            _returnVal1ShippingAddress.setAddress(-1493650729);
            _returnVal1ShippingAddress.setCountry("Country1610660606");
            _returnVal1ShippingAddress.setCounty("County1434801246");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress-1948398323");
            _returnVal1ShippingAddress.setTownVillage("TownVillage1389043109");
            _returnVal1ShippingAddress.setZipcode("Zipcode-2015223686");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
