
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.mycourierservice;



import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.apache.log4j.Logger;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-04-15T10:32:23.279+03:00
 * Generated source version: 2.6.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "CourierServiceService",
                      portName = "CourierServicePort",
                      targetNamespace = "http://mycourierservice.idu0080.ttu/",
                      wsdlLocation = "file:/C:/Users/Gummel/ttu_mag2/veebiteenus/My_service/WebContent/WEB-INF/wsdl/couriers.wsdl",
                      endpointInterface = "ttu.idu0080.mycourierservice.CourierService")
                      
public class CourierServiceImpl implements CourierService {

    private static final Logger LOG = Logger.getLogger(CourierServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.mycourierservice.CourierService#getAllCouriers(*
     */
    public java.util.List<ttu.idu0080.mycourierservice.Courier> getAllCouriers() { 
        
    	LOG.info("------------------------------------------");
    	
    	LOG.info("------------------------------------------");
    	LOG.info("CourierService starts");
        try {
            java.util.List<ttu.idu0080.mycourierservice.Courier> _return = new java.util.ArrayList<ttu.idu0080.mycourierservice.Courier>();
            ttu.idu0080.courierservice.client.CourierService_CourierServicePort_Client courierService =
         		   new ttu.idu0080.courierservice.client.CourierService_CourierServicePort_Client();
            java.util.List<ttu.idu0080.courierservice.client.Courier> couriers = courierService.getAllCouriers();
            for (ttu.idu0080.courierservice.client.Courier courier : couriers) {
            	ttu.idu0080.mycourierservice.Courier returnCourier = new ttu.idu0080.mycourierservice.Courier();
        		returnCourier.setCourierId(courier.getEnterprise());
        		returnCourier.setName(courier.getName());
        		LOG.info("Courier:["+returnCourier.getName()+"]");
        	   _return.add(returnCourier);
    		}
            LOG.info("CourierService ends");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        
    }

}
