package ttu.idu0080.mycourierservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-04-15T10:32:23.389+03:00
 * Generated source version: 2.6.16
 * 
 */
@WebService(targetNamespace = "http://mycourierservice.idu0080.ttu/", name = "CourierService")
@XmlSeeAlso({ObjectFactory.class})
public interface CourierService {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://mycourierservice.idu0080.ttu/CourierService/getAllCouriersRequest", output = "http://mycourierservice.idu0080.ttu/CourierService/getAllCouriersResponse")
    @RequestWrapper(localName = "getAllCouriers", targetNamespace = "http://mycourierservice.idu0080.ttu/", className = "ttu.idu0080.mycourierservice.GetAllCouriers")
    @WebMethod
    @ResponseWrapper(localName = "getAllCouriersResponse", targetNamespace = "http://mycourierservice.idu0080.ttu/", className = "ttu.idu0080.mycourierservice.GetAllCouriersResponse")
    public java.util.List<ttu.idu0080.mycourierservice.Courier> getAllCouriers();
}
