
package ttu.idu0080.offerservice.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-04-15T10:36:58.804+03:00
 * Generated source version: 2.6.16
 * 
 */
public final class OfferService_OfferServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://offerservice.idu0080.ttu/", "OfferServiceService");

    public OfferService_OfferServicePort_Client() {
    }

    public ttu.idu0080.offerservice.client.Offer getOffer(int courierId, ttu.idu0080.offerservice.client.Order order) throws Exception {
	URL wsdlURL = OfferServiceService.WSDL_LOCATION;
	ttu.idu0080.offerservice.client.Offer _getOffer__return = null ;
   	OfferServiceService ss = new OfferServiceService(wsdlURL, SERVICE_NAME);
    OfferService port = ss.getOfferServicePort();   
     _getOffer__return = port.getOffer(courierId, order);
		 return _getOffer__return;
	 }

}
