
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.offerservice.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-04-15T10:36:58.882+03:00
 * Generated source version: 2.6.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "OfferServiceService",
                      portName = "OfferServicePort",
                      targetNamespace = "http://offerservice.idu0080.ttu/",
                      wsdlLocation = "http://localhost:8080/My_service/services/OfferServicePort?wsdl",
                      endpointInterface = "ttu.idu0080.offerservice.client.OfferService")
                      
public class OfferServiceImpl implements OfferService {

    private static final Logger LOG = Logger.getLogger(OfferServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.offerservice.client.OfferService#getOffer(int  courierId ,)ttu.idu0080.offerservice.client.Order  order )*
     */
    public ttu.idu0080.offerservice.client.Offer getOffer(int courierId,ttu.idu0080.offerservice.client.Order order) { 
        LOG.info("Executing operation getOffer");
        System.out.println(courierId);
        System.out.println(order);
        try {
            ttu.idu0080.offerservice.client.Offer _return = new ttu.idu0080.offerservice.client.Offer();
            _return.setOfferId("OfferId1693205912");
            _return.setPrice(0.77425903f);
            _return.setDeliveryDate(-1615930917);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
