package ttu.idu0080.offerservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-04-15T10:36:58.913+03:00
 * Generated source version: 2.6.16
 * 
 */
@WebService(targetNamespace = "http://offerservice.idu0080.ttu/", name = "OfferService")
@XmlSeeAlso({ObjectFactory.class})
public interface OfferService {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://offerservice.idu0080.ttu/OfferService/getOfferRequest", output = "http://offerservice.idu0080.ttu/OfferService/getOfferResponse")
    @RequestWrapper(localName = "getOffer", targetNamespace = "http://offerservice.idu0080.ttu/", className = "ttu.idu0080.offerservice.client.GetOffer")
    @WebMethod
    @ResponseWrapper(localName = "getOfferResponse", targetNamespace = "http://offerservice.idu0080.ttu/", className = "ttu.idu0080.offerservice.client.GetOfferResponse")
    public ttu.idu0080.offerservice.client.Offer getOffer(
        @WebParam(name = "courier_id", targetNamespace = "")
        int courierId,
        @WebParam(name = "order", targetNamespace = "")
        ttu.idu0080.offerservice.client.Order order
    );
}
