
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.transportorderservice.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-04-15T10:37:34.796+03:00
 * Generated source version: 2.6.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "TransportOrderServiceService",
                      portName = "TransportOrderServicePort",
                      targetNamespace = "http://transportorderservice.idu0080.ttu/",
                      wsdlLocation = "http://localhost:8080/My_service/services/TransportOrderServicePort?wsdl",
                      endpointInterface = "ttu.idu0080.transportorderservice.client.TransportOrderService")
                      
public class TransportOrderServiceImpl implements TransportOrderService {

    private static final Logger LOG = Logger.getLogger(TransportOrderServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.transportorderservice.client.TransportOrderService#orderTransport(java.lang.String  offerId )*
     */
    public java.lang.String orderTransport(java.lang.String offerId) { 
        LOG.info("Executing operation orderTransport");
        System.out.println(offerId);
        try {
            java.lang.String _return = "_return1971938038";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
