package ttu.idu0080.transportorderservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-04-15T10:37:34.827+03:00
 * Generated source version: 2.6.16
 * 
 */
@WebService(targetNamespace = "http://transportorderservice.idu0080.ttu/", name = "TransportOrderService")
@XmlSeeAlso({ObjectFactory.class})
public interface TransportOrderService {

    @WebResult(name = "tracking_number", targetNamespace = "")
    @Action(input = "http://transportorderervice.idu0080.ttu/TransportOrderService/orderTransportRequest", output = "http://transportorderservice.idu0080.ttu/TransportOrderService/orderTransportResponse")
    @RequestWrapper(localName = "orderTransport", targetNamespace = "http://transportorderservice.idu0080.ttu/", className = "ttu.idu0080.transportorderservice.client.OrderTransport")
    @WebMethod
    @ResponseWrapper(localName = "orderTransportResponse", targetNamespace = "http://transportorderservice.idu0080.ttu/", className = "ttu.idu0080.transportorderservice.client.OrderTransportResponse")
    public java.lang.String orderTransport(
        @WebParam(name = "offer_id", targetNamespace = "")
        java.lang.String offerId
    );
}
