
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.mycourierservice.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-04-15T10:36:04.928+03:00
 * Generated source version: 2.6.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "CourierServiceService",
                      portName = "CourierServicePort",
                      targetNamespace = "http://mycourierservice.idu0080.ttu/",
                      wsdlLocation = "http://localhost:8080/My_service/services/CourierServicePort?wsdl",
                      endpointInterface = "ttu.idu0080.mycourierservice.client.CourierService")
                      
public class CourierServiceImpl implements CourierService {

    private static final Logger LOG = Logger.getLogger(CourierServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.mycourierservice.client.CourierService#getAllCouriers(*
     */
    public java.util.List<ttu.idu0080.mycourierservice.client.Courier> getAllCouriers() { 
        LOG.info("Executing operation getAllCouriers");
        try {
            java.util.List<ttu.idu0080.mycourierservice.client.Courier> _return = new java.util.ArrayList<ttu.idu0080.mycourierservice.client.Courier>();
            ttu.idu0080.mycourierservice.client.Courier _returnVal1 = new ttu.idu0080.mycourierservice.client.Courier();
            _returnVal1.setCourierId(1346862505);
            _returnVal1.setName("Name-1208090712");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
