
package ttu.idu0080.bp.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.16
 * Wed Apr 15 12:11:22 EEST 2015
 * Generated source version: 2.6.16
 */

@XmlRootElement(name = "runOrderShipmentBusinessProcessResponse", namespace = "http://bp.idu0080.ttu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "runOrderShipmentBusinessProcessResponse", namespace = "http://bp.idu0080.ttu/")

public class RunOrderShipmentBusinessProcessResponse {


}

