
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.transportorderservice;



import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.apache.log4j.Logger;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-04-15T10:33:06.887+03:00
 * Generated source version: 2.6.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "TransportOrderServiceService",
                      portName = "TransportOrderServicePort",
                      targetNamespace = "http://transportorderservice.idu0080.ttu/",
                      wsdlLocation = "file:/C:/Users/Gummel/ttu_mag2/veebiteenus/My_service/WebContent/WEB-INF/wsdl/transportOrder.wsdl",
                      endpointInterface = "ttu.idu0080.transportorderservice.TransportOrderService")
                      
public class TransportOrderServiceImpl implements TransportOrderService {

    private static final Logger LOG = Logger.getLogger(TransportOrderServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.transportorderservice.TransportOrderService#orderTransport(java.lang.String  offerId )*
     */
    public java.lang.String orderTransport(java.lang.String offerId) { 
    	LOG.info("------------------------------------------");
    	LOG.info("------------------------------------------");
    	LOG.info("TransportOrderService starts");
        

        try {
            StringBuilder returnVal = new StringBuilder();
          returnVal.append(offerId.toLowerCase());
          returnVal.append("#");
          returnVal.append(formatDate());
          LOG.info("Pakkumisele (order_id):["+offerId+"] vastav tellimus registreeritud. Saadetise tracking number: [" + returnVal+"]");
          LOG.info("TransportOrderService ends");
          return returnVal +"";
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
    
    public String formatDate() {
        java.util.Date date = new java.util.Date(); // your date
        java.util.Calendar cal = java.util.Calendar.getInstance();
        cal.setTime(date);
        int year = cal.get(java.util.Calendar.YEAR);
        int month = cal.get(java.util.Calendar.MONTH);
        int day = cal.get(java.util.Calendar.DAY_OF_MONTH);
        if(month < 10) return year+"0"+month+""+day;
        else if(day<10)return year+""+month+"0"+day;
        else if(month < 10 && day < 10) return year+"0"+month+"0"+day;
        return year+""+month+""+day+"";
    }

}
