package ttu.idu0080.transportorderservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-04-15T10:33:06.965+03:00
 * Generated source version: 2.6.16
 * 
 */
@WebServiceClient(name = "TransportOrderServiceService", 
                  wsdlLocation = "file:/C:/Users/Gummel/ttu_mag2/veebiteenus/My_service/WebContent/WEB-INF/wsdl/transportOrder.wsdl",
                  targetNamespace = "http://transportorderservice.idu0080.ttu/") 
public class TransportOrderServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://transportorderservice.idu0080.ttu/", "TransportOrderServiceService");
    public final static QName TransportOrderServicePort = new QName("http://transportorderservice.idu0080.ttu/", "TransportOrderServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Gummel/ttu_mag2/veebiteenus/My_service/WebContent/WEB-INF/wsdl/transportOrder.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TransportOrderServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Olesja/workspace_/My_service/WebContent/WEB-INF/wsdl/transportOrder.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TransportOrderServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransportOrderServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransportOrderServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TransportOrderServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TransportOrderServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TransportOrderServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TransportOrderService
     */
    @WebEndpoint(name = "TransportOrderServicePort")
    public TransportOrderService getTransportOrderServicePort() {
        return super.getPort(TransportOrderServicePort, TransportOrderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransportOrderService
     */
    @WebEndpoint(name = "TransportOrderServicePort")
    public TransportOrderService getTransportOrderServicePort(WebServiceFeature... features) {
        return super.getPort(TransportOrderServicePort, TransportOrderService.class, features);
    }

}
